### ISSUE TITLE
Reduce unnecessary requests

### ISSUE THREAD

**Issue by WoeOm** [smartxworks/sunmao-ui#597]
**Version**
  "editor version": "0.7.4",

**Reproduction link**

**Steps to reproduce**
After setting the api, the editor will request 3 times each time. Expect one request to reduce unnecessary requests

**What is expected?**

**What is actually happening?**
<img width="497" alt="image" src="https://user-images.githubusercontent.com/7368203/189041472-2279ab76-2d49-4e82-b570-111185e7015a.png">

**Comment by tanbowensg** [comment]
I could because you use expressions in api. Everytime expression value changes, the api will run and the request will be sent. I you need to control the timing of sending request, you can set the `lazy` to be true. Then the request will only be sent when the `triggerFetch` method of api is called.
![截屏2022-09-09 上午10 01 07](https://user-images.githubusercontent.com/12260952/189256592-f9d86d5c-605e-49ab-950e-58de95f7ab35.png)
